version: '3.3'
services:
  mysql:
    container_name: mysql-local
#    hostname: mysql-local
    image: mysql:8
    restart: always
    command: [--default-authentication-plugin=mysql_native_password]
    environment:
      MYSQL_DATABASE: 'my_job'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'root_pass'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
