# Generated by Django 3.0.6 on 2020-08-04 10:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('type_employment', models.CharField(max_length=2, null=True)),
                ('company', models.CharField(max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('date_start', models.DateField(default=datetime.datetime.now, null=True)),
                ('date_end', models.DateField(default=datetime.datetime.now, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=100)),
                ('degree', models.CharField(blank=True, max_length=100)),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('date_start', models.DateField(blank=True, default=datetime.datetime.now)),
                ('date_end', models.DateField(blank=True, default=datetime.datetime.now)),
                ('description', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
