# Generated by Django 3.0.6 on 2020-08-03 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='user_experience',
        ),
    ]
