# Generated by Django 3.0.6 on 2020-09-01 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_certificate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='date_start',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
