# Generated by Django 3.0.6 on 2020-09-02 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200901_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='checkbox',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='date_end',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
