# Generated by Django 3.0.6 on 2020-09-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200902_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='checkbox',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='education',
            name='checkbox',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
