# Generated by Django 3.0.6 on 2020-09-02 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200902_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='checkbox',
        ),
    ]
