# Generated by Django 3.0.6 on 2020-09-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='common_information',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
