# Generated by Django 3.0.6 on 2020-09-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200907_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='region',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
    ]
