# Generated by Django 3.0.6 on 2020-09-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200909_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='blog/static/img/unnamed.jpg', null=True, upload_to=''),
        ),
    ]
