# Generated by Django 3.0.6 on 2020-09-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20200909_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='/unnamed.jpg', null=True, upload_to=''),
        ),
    ]
