# Generated by Django 3.0.6 on 2020-09-09 10:16

from django.db import migrations
import django_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20200909_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=django_fields.fields.DefaultStaticImageField(blank=True, null=True, upload_to=''),
        ),
    ]
